AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to launch an EC2 instance with Streamlit application behind an ALB.

Parameters:
  SSHRegionIPsAllowed:
    Description: Provides EC2 SSH access for CIDR range in a region. (Default is us-west-2)
    Type: String
    Default: 18.237.140.160/29
    AllowedValues:
      - 18.237.140.160/29
      - 18.206.107.24/29
      - 43.196.20.40/29
      - 43.192.155.8/29
      - 18.252.4.0/30
      - 15.200.28.80/30
      - 13.244.121.196/30
      - 43.198.192.104/29
      - 3.112.23.0/29
      - 13.209.1.56/29
      - 15.168.105.160/29
      - 13.233.177.0/29
      - 18.60.252.248/29
      - 3.0.5.32/29
      - 13.239.158.0/29
      - 43.218.193.64/29
      - 16.50.248.80/29
      - 35.183.92.176/29
      - 40.176.213.168/29
      - 3.120.181.40/29
      - 16.63.77.8/29
      - 13.48.4.200/30
      - 15.161.135.164/30
      - 18.101.90.48/29
      - 18.202.216.48/29
      - 3.8.37.24/29
      - 35.180.112.80/29
      - 51.16.183.224/29
      - 3.29.147.40/29
      - 16.24.46.56/29
      - 18.228.70.32/29
      - 3.16.146.0/29
      - 13.52.6.112/29
  VPCCIDR:
    Description: VPC CIDR
    Type: String
    Default: 10.0.0.0/16
  PublicSubnet1CIDR:
    Description: First Public Subnet CIDR
    Type: String
    Default: 10.0.1.0/24
  PublicSubnet2CIDR:
    Description: Second Public Subnet CIDR
    Type: String
    Default: 10.0.3.0/24
  PublicSubnet3CIDR:
    Description: Third Public Subnet CIDR
    Type: String
    Default: 10.0.4.0/24
  PrivateSubnetCIDR:
    Description: Private Subnet CIDR
    Type: String
    Default: 10.0.2.0/24
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3.small
    AllowedValues:
      - t3.small
      - t3.medium
      - t3.large

Resources:
  # Create a VPC
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VPCCIDR
      Tags:
        - Key: Name
          Value: Bedrock-VPC

  # Create the first Public Subnet
  PublicSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: Bedrock-Public-Subnet-1

  # Create the second Public Subnet
  PublicSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet2CIDR
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: Bedrock-Public-Subnet-2

  # Create the third Public Subnet in a different Availability Zone
  PublicSubnet3:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet3CIDR
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [2, !GetAZs '']
      Tags:
        - Key: Name
          Value: Bedrock-Public-Subnet-3

  # Create a Private Subnet
  PrivateSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetCIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Bedrock-Private-Subnet

  # Create an Internet Gateway
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: Bedrock-InternetGateway

  # Attach the Internet Gateway to the VPC
  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Create a NAT Gateway
  EIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc

  NATGateway:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      AllocationId: !GetAtt EIP.AllocationId
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key: Name
          Value: Bedrock-NATGateway

  # Create a Route Table for the Public Subnets
  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Bedrock-Public-RouteTable

  # Create a Route Table for the Private Subnet
  PrivateRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Bedrock-Private-RouteTable

  # Create a Route in the Public Route Table to the Internet
  PublicRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # Create a Route in the Private Route Table to the NAT Gateway
  PrivateRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway

  # Associate the Public Subnets with the Public Route Table
  PublicSubnet1RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet3RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnet3
      RouteTableId: !Ref PublicRouteTable

  # Associate the Private Subnet with the Private Route Table
  PrivateSubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PrivateRouteTable

  # Security Group for ALB
  ALBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow HTTP traffic to ALB
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  # Security Group for EC2 instance, allowing traffic only from ALB
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow traffic from ALB
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8501
          ToPort: 8501
          SourceSecurityGroupId: !Ref ALBSecurityGroup

  # Create an IAM Role for the EC2 instance to use SSM and Amazon Bedrock
  EC2Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

  # Create an Instance Profile for the EC2 instance
  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref EC2Role

  # Create the EC2 instance in the Private Subnet
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Sub "{{resolve:ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id}}"
      IamInstanceProfile: !Ref InstanceProfile
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      SubnetId: !Ref PrivateSubnet
      EbsOptimized: true
      Monitoring: true
      Tags:
        - Key: Name
          Value: EC2-Streamlit-App
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
          apt-get update -y
          apt-get upgrade -y
          apt-get install -y python3-pip git ec2-instance-connect
          git clone https://github.com/build-on-aws/bedrock-agent-txt2sql.git /home/ubuntu/app
          pip3 install -r /home/ubuntu/app/streamlit_app/requirements.txt
          nohup streamlit run /home/ubuntu/app/streamlit_app/app.py > streamlit.log 2>&1 &

  # Create an Application Load Balancer
  ALB:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: Bedrock-ALB
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
        - !Ref PublicSubnet3
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'

  # Create a Target Group for the ALB
  TargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Name: Bedrock-TargetGroup
      VpcId: !Ref VPC
      Protocol: HTTP
      Port: 8501
      TargetType: instance
      HealthCheckProtocol: HTTP
      HealthCheckPort: '8501'
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200-399

  # Listener for ALB to route traffic to Target Group
  ALBListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP

  # Register the EC2 instance with the Target Group
  RegisterTarget:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroupAttachment'
    Properties:
      TargetGroupArn: !Ref TargetGroup
      TargetId: !Ref EC2Instance
      Port: 8501

Outputs:
  LoadBalancerDNSName:
    Description: DNS name of the Load Balancer
    Value: !GetAtt ALB.DNSName
